### PR TITLE
Allow filter by recording type in search recording screen

### LINKED ISSUE #18: Support both audio & video recordings on recordings pages
Similar to TheCacophonyProject/cacophony-web#113

- [x] Search returns video and audio files
- [ ] Allow for filter by type (audio, video or both)
- [x] Display type (audio or video) in the table
- [x] Add support for audio on the view recording page

### PR DESCRIPTION
**Pull request by arthurmcgregor**
Closes #18 

Should be merged after #61 because I didn't manage my branches too well in my fork sorry! It's really only the last commit that is different here.

### CODE REVIEW

**Comment by arthurmcgregor** [comment]
The duration field was always slightly out - even before I added the recording type input! But fixed now. Perhaps merge this now and add 2 and 3 to the backlog...

**Comment by mjs** [comment]
Thanks for fixing. Would you mind adding issues for 2 and 3?

**Comment by arthurmcgregor** [comment]
Issues for 2 and 3 created and added to v1 milestone

**Comment by mjs** [comment]
Thanks @arthurmcgregor

**Pull request merged**
