### PR TITLE
Update favicons and titlebar image

### LINKED ISSUE #52: Include favicons in builds
`index.template.ejs` currently refers to the favicons in `src/assets/favicon` which only works when the frontend is run in dev mode. Figure out how to get them included in the build and refer to them in the `dist` output instead. I'm pretty sure there's a way to get webpack to treat the favicons as dependencies so they get handled correctly.

### PR DESCRIPTION
**Pull request by jimmykl**
More variations of the favicon for browsers and devices
Added SVG version of navbar logo with PNG fallback

Fixes #52.

### CODE REVIEW

**Comment by mjs** [comment]
This needs to be updated with respect to recent changes in master.

Regarding index.html, it no longer exists and is now being generated from a template (see index.template.ejs).

I'm happy to help getting it updated if you need.

**Comment by mjs** [comment]
#52 also related to this (but can be done separately)

**Comment by jimmykl** [comment]
@mjs If you could help that would be cool. Thought I'd fetched the latest version but must have missed something.

I'm not familiar with webpack (yet) I found this which looks like it could do the trick https://github.com/jantimon/favicons-webpack-plugin but someone else is probably better placed to tackle #52

**Comment by mjs** [comment]
@jimmykl You probably did pull the latest code when you started but I landed a bunch of stuff since. I'll submit a PR to your branch to get things sorted.

**Pull request merged**
